name: Docker Compose Actions Workflow
on:
  push:
      branches:
        - main
      tags:
        - 'v*.*.*'
jobs:
  test:
    runs-on: self-hosted
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Build the dockercompose stack
        run: docker-compose up -d --build

      - uses: actions/checkout@v2
      - name: push docker images
        run: docker-compose push



